use anyhow::Result;
use std::fs;
use std::path::Path;

const SKILL_VERSION: &str = env!("CARGO_PKG_VERSION");

const SKILL_TEMPLATE: &str = r#"---
description: How to use the Navi CLI for code navigation
navi-version: $$VERSION$$
---

# Navi — Headless Code Navigation CLI

Navi is a Rust-based CLI tool built on `ast-grep` that provides AI-optimized code structure navigation. All output is clean plain text with absolute line numbers — no ANSI colors, no noise.

> See [COMMANDS.md](./COMMANDS.md) for the full reference of all supported commands.

## Quick Reference

| Command | Purpose |
|---------|---------|
| `navi list <FILE>` | Extract file skeleton (collapsed bodies) |
| `navi jump <SYMBOL>` | Jump to symbol definition |
| `navi refs <SYMBOL>` | Find all references to a symbol |
| `navi read <FILE> <RANGE>` | Read exact line range |
| `navi tree [DIR]` | Recursive directory skeleton |
| `navi outline [DIR]` | Project architecture overview |
| `navi callers <SYMBOL>` | Find call-sites (excludes imports) |
| `navi deps <FILE>` | Show file import/reverse-import graph |
| `navi types <SYMBOL>` | Recursively expand type definitions |
| `navi scope <FILE> <LINE>` | Show enclosing scope at a line |
| `navi diff <SYMBOL>` | Git diff filtered to a symbol |
| `navi sg [ARGS...]` | Passthrough to ast-grep CLI |
| `navi init [DIR]` | Write/update this skill document |

## Recommended Workflow

1. **Orient** → `navi outline` or `navi tree` to map the project
2. **Explore** → `navi list <file>` to see a file's structure
3. **Dive** → `navi jump <symbol>` to read a definition
4. **Assess** → `navi refs <symbol>` or `navi callers <symbol>` to gauge blast radius
5. **Trace types** → `navi types <symbol> --depth 2` to understand data shapes
6. **Slice** → `navi read <file> <range>` to grab exact lines
7. **Diff** → `navi diff <symbol>` to see recent changes to a symbol

## Exit Codes

| Code | Meaning |
|------|---------|
| `0`  | Success (even if no results found — check stdout) |
| `1`  | File path error or file does not exist |
| `2`  | Argument parsing failure (bad range format, etc.) |
| `3`  | AST engine crash or internal error |

## Supported Languages

Navi supports 26+ languages including: Rust, TypeScript, JavaScript, Python, Go, Java, C, C++, Ruby, Swift, Kotlin, Scala, PHP, Lua, Bash, CSS, HTML, Solidity, Elixir, Haskell, and more.
"#;

const COMMANDS_TEMPLATE: &str = r#"# Navi Commands Reference

> Auto-generated by `navi init` — version $$VERSION$$

---

## 1. `navi list <FILE>` — Extract File Skeleton

Show all top-level definitions (functions, classes, interfaces, structs) in a file with bodies collapsed to `{ ... }`.

```bash
navi list src/auth/user_service.ts
```

```
File: src/auth/user_service.ts
  12: export interface User { ... }
  25: export class UserService { ... }
  30:   public async login(req: LoginReq): Promise<Token> { ... }
  88:   private hashPassword(pwd: string): string { ... }
```

**When to use:** First step to understand a file's structure before diving deeper.

---

## 2. `navi jump <SYMBOL> [--path <DIR>] [--all]` — Jump to Definition

Find and display the complete source code of a symbol definition with ±3 lines of context.

| Flag | Description |
|------|-------------|
| `--path <DIR>` | Directory to search in (default: CWD) |
| `--all` | Show all definitions instead of just the first |

```bash
navi jump login --path src/
navi jump UserService --all
```

**When to use:** To read the full implementation of an unfamiliar symbol.

---

## 3. `navi refs <SYMBOL> [--path <DIR>]` — Find All References

Locate every file and line where a symbol is referenced.

| Flag | Description |
|------|-------------|
| `--path <DIR>` | Directory to search in (default: CWD) |

```bash
navi refs login --path src/
```

```
Found 3 references for 'login':
- src/api/routes.ts: 45 | const token = await userService.login(req.body);
- src/tests/auth.test.ts: 12 | const res = await service.login(mockUser);
- src/auth/user_service.ts: 30 | public async login(req: LoginReq): Promise<Token> {
```

**When to use:** Before modifying a function signature or renaming a symbol. Assess blast radius.

---

## 4. `navi read <FILE> <START-END>` — Read Line Range

Read a precise slice of a file by line numbers (1-indexed, inclusive). No AST parsing — just raw lines.

```bash
navi read src/main.rs 10-25
```

**When to use:** When you already know the exact lines you need.

---

## 5. `navi tree [DIR]` — Recursive Directory Skeleton

Recursively walk a directory and run `list` on every supported source file, producing a full project skeleton.

```bash
navi tree src/
navi tree          # defaults to CWD
```

**When to use:** To get a bird's-eye view of all definitions across a codebase or subdirectory.

---

## 6. `navi outline [DIR]` — Project Architecture Overview

Show a high-level project outline with package/crate organization and file counts.

```bash
navi outline
navi outline packages/
```

**When to use:** First command to run on an unfamiliar project to understand its structure.

---

## 7. `navi callers <SYMBOL> [--path <DIR>]` — Find Call-Sites

Find actual call-site usages of a symbol, excluding import statements and type annotations.

| Flag | Description |
|------|-------------|
| `--path <DIR>` | Directory to search in (default: CWD) |

```bash
navi callers handleRequest --path src/
```

**When to use:** To see where a function is actually *invoked* (not just imported).

---

## 8. `navi deps <FILE>` — File Dependencies

Show what a file imports and which other files import it (reverse dependencies).

```bash
navi deps src/auth/user_service.ts
```

**When to use:** To understand a file's dependency relationships before refactoring.

---

## 9. `navi types <SYMBOL> [--path <DIR>] [--depth <N>]` — Recursive Type Expansion

Look up a type/struct/interface definition and recursively expand all types it references.

| Flag | Description |
|------|-------------|
| `--path <DIR>` | Directory to search in (default: CWD) |
| `--depth <N>` | Max recursion depth (default: 1) |

```bash
navi types UserConfig --depth 2
```

**When to use:** To understand complex data shapes and their nested type dependencies.

---

## 10. `navi scope <FILE> <LINE>` — Show Enclosing Scope

Given a file and line number, show the enclosing function/method scope that contains that line.

```bash
navi scope src/main.rs 45
```

**When to use:** When you see a line number (e.g. from an error trace) and need to understand its context.

---

## 11. `navi diff <SYMBOL> [--path <DIR>]` — Symbol-Filtered Git Diff

Show the git diff filtered to only the hunks that touch a specific symbol's definition.

| Flag | Description |
|------|-------------|
| `--path <DIR>` | Directory to search in (default: CWD) |

```bash
navi diff login --path src/
```

**When to use:** To see exactly what changed in a specific function between commits.

---

## 12. `navi sg [ARGS...]` — ast-grep Passthrough

Forward arguments directly to the underlying `ast-grep` CLI (run, scan, test, etc.).

```bash
navi sg run --pattern 'console.log($$$)' --lang typescript
navi sg scan
```

**When to use:** For advanced AST pattern matching beyond Navi's built-in commands.

---

## 13. `navi init [DIR]` — Initialize Skill Documents

Create or update the Navi skill documents (`SKILL.md` and `COMMANDS.md`) in `.agent/skills/navi/`. Automatically detects version changes and updates in place.

```bash
navi init
navi init /path/to/project
```

**When to use:** Run once per project to teach AI agents about Navi's capabilities.
"#;

fn skill_content() -> String {
    SKILL_TEMPLATE.replace("$$VERSION$$", SKILL_VERSION)
}

fn commands_content() -> String {
    COMMANDS_TEMPLATE.replace("$$VERSION$$", SKILL_VERSION)
}

/// Extract the navi-version value from SKILL.md frontmatter.
fn extract_version(content: &str) -> Option<&str> {
    let mut in_frontmatter = false;
    for line in content.lines() {
        if line == "---" {
            if !in_frontmatter {
                in_frontmatter = true;
                continue;
            } else {
                break;
            }
        }
        if in_frontmatter {
            if let Some(version) = line.strip_prefix("navi-version:") {
                return Some(version.trim());
            }
        }
    }
    None
}

pub fn run(path: Option<&Path>) -> Result<()> {
    let base = path.unwrap_or_else(|| Path::new("."));
    let agent_dir = base.join(".agent");
    let skill_dir = agent_dir.join("skills").join("navi");
    let skill_file = skill_dir.join("SKILL.md");
    let commands_file = skill_dir.join("COMMANDS.md");
    let skill = skill_content();
    let commands = commands_content();

    if skill_file.exists() {
        let existing = fs::read_to_string(&skill_file)?;
        let existing_ver = extract_version(&existing);

        if existing_ver == Some(SKILL_VERSION) {
            // Ensure COMMANDS.md also exists even if SKILL.md is current
            if !commands_file.exists() {
                fs::write(&commands_file, &commands)?;
                println!(
                    "Created COMMANDS.md (v{SKILL_VERSION}): {}",
                    commands_file.display()
                );
            }
            println!(
                "Skill file is up to date (v{}): {}",
                SKILL_VERSION,
                skill_file.display()
            );
            return Ok(());
        }

        // Version mismatch or missing — update both files
        fs::write(&skill_file, &skill)?;
        fs::write(&commands_file, &commands)?;
        match existing_ver {
            Some(v) => println!(
                "Updated Navi skill documents ({v} → {SKILL_VERSION}): {}",
                skill_dir.display()
            ),
            None => println!(
                "Updated Navi skill documents (→ v{SKILL_VERSION}): {}",
                skill_dir.display()
            ),
        }
        return Ok(());
    }

    fs::create_dir_all(&skill_dir)?;
    fs::write(&skill_file, &skill)?;
    fs::write(&commands_file, &commands)?;

    println!(
        "Created Navi skill documents (v{SKILL_VERSION}) at: {}",
        skill_dir.display()
    );
    Ok(())
}
